# -*- coding: utf-8 -*-
"""Ecomdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12QvUw3l6VC6Sbj2ZvIjCegt-jS1Uw1AN
"""

import pandas as pd
import numpy as np

# 1. Create Product Master Data
products_data = {
    'product_id': [101, 102, 103, 104, 105],
    'product_name': ['Wireless Mouse', 'Gaming Laptop', 'Desk Lamp', 'Office Chair', 'USB-C Cable'],
    'category': ['Electronics', 'Electronics', 'Furniture', 'Furniture', 'Accessories'],
    'cogs': [15, 800, 20, 150, 5]  # Cost of Goods Sold (What it costs the company)
}
df_products = pd.DataFrame(products_data)

# 2. Create Orders Data (1000 rows)
np.random.seed(42)
num_orders = 1000

orders_data = {
    'order_id': range(1001, 1001 + num_orders),
    'product_id': np.random.choice([101, 102, 103, 104, 105], num_orders),
    'sale_price': np.random.choice([25, 1200, 45, 250, 15], num_orders),
    'discount_amount': np.random.choice([0, 5, 10, 50, 100], num_orders),
    'shipping_cost': np.random.uniform(5, 60, num_orders).round(2), # Some shipping is very expensive!
    'region': np.random.choice(['North', 'South', 'East', 'West'], num_orders)
}
df_orders = pd.DataFrame(orders_data)

# Save to CSV files
df_products.to_csv('products.csv', index=False)
df_orders.to_csv('orders.csv', index=False)

print("Data Generated Successfully! You now have 'orders.csv' and 'products.csv'.")